const BackerData = [
    {
        id: Math.random(),
        image: '/backer/dext_force.webp',
        name: 'dext_force',
        className: 'dextForce',
        url: 'https://twitter.com/DextForce/status/1465146264941649921',
    },
    {
        id: Math.random(),
        image: '/backer/kyber_alumni_fund.webp',
        name: 'kyber_alumni_fund',
        className: 'kyberAlumniFund',
        url: '',
    },
    {
        id: Math.random(),
        image: '/backer/basic_capital.webp',
        name: 'basic_capital',
        className: 'basicCapital',
        url: 'https://twitter.com/BasicsCapital/status/1461603181117333509?s=20',
    },
    {
        id: Math.random(),
        image: '/backer/au21_capital.webp',
        name: 'kyber_alumni_fund',
        className: 'au21Capital',
        url: '',
    },
    {
        id: Math.random(),
        image: '/backer/maven_capital.webp',
        name: 'maven_capital',
        className: 'mavenCapital',
        url: 'https://twitter.com/DextForce/status/1465146264941649921?s=20',
    },
    {
        id: Math.random(),
        image: '/backer/dct.webp',
        name: 'dct',
        className: 'dct',
        url: 'https://t.me/DesiCryptoTrades/1149',
    },
    {
        id: Math.random(),
        image: '/backer/golden_shovel.webp',
        name: 'golden_shovel',
        className: 'goldenShovel',
        url: 'https://www.goldenshovel.io/',
    },
    {
        id: Math.random(),
        image: '/backer/zbs_capital.webp',
        name: 'zbs_capital',
        className: 'zbsCapital',
        url: '',
    },
    {
        id: Math.random(),
        image: '/backer/good_games.webp',
        name: 'good_games',
        className: 'goodGames',
        url: 'https://twitter.com/goodgamesguild/status/1466636539782258690',
    },
    {
        id: Math.random(),
        image: '/backer/dutch_crypto_investor.webp',
        name: 'dutch_crypto_investor',
        className: 'dutchCryptox',
        url: 'https://medium.com/@DutchCryptoInvestors/90cde13276ca',
    },
    {
        id: Math.random(),
        image: '/backer/kiwi_group.webp',
        name: 'kiwi_group',
        className: 'kiwiGroup',
        url: 'https://twitter.com/_KiwiGROUP_/status/1464200220871254023',
    },
    {
        id: Math.random(),
        image: '/backer/crypto_dorm_func.webp',
        name: 'crypto_dorm_func',
        className: 'cryptoDorm',
        url: 'https://www.cryptodormfund.org/',
    },
    {
        id: Math.random(),
        image: '/backer/infinity.webp',
        name: 'infinity',
        className: 'infinity',
        url: 'https://twitter.com/InfinityVC_/status/1462816342151602181?s=20',
    },
    {
        id: Math.random(),
        image: '/backer/lavender.webp',
        name: 'lavender',
        className: 'lavender',
        url: 'https://twitter.com/Lavender_VC/status/1463824841719656463?s=20',
    },
    {
        id: Math.random(),
        image: '/backer/kyros_ventures.webp',
        name: 'kyros_ventures',
        className: 'kyrosVentures',
        url: 'https://medium.com/kingspeeddocs/king-speed-welcomes-kyros-ventures-as-our-strategic-partner-bc7c9a06f3dd',
    },
    {
        id: Math.random(),
        image: '/backer/dream_boat.webp',
        name: 'dream_boat',
        className: 'dreamBoat',
        url: 'https://twitter.com/Dreamboat_id/status/1463861940732657667?s=20',
    },
    {
        id: Math.random(),
        image: '/backer/mh_ventures.webp',
        name: 'mh_ventures',
        className: 'mhVentures',
        url: 'https://twitter.com/MH_Ventures/status/1463911542743871511?s=20',
    },
    {
        id: Math.random(),
        image: '/backer/peech_capital.png',
        name: 'peech_capital',
        className: 'peechCapital',
        url: '',
    },
    {
        id: Math.random(),
        image: '/backer/kv_ventures.png',
        name: 'kv_ventures',
        className: 'kvVentures',
        url: '',
    },
]

export default BackerData
